# Generated by Django 2.2.3 on 2019-07-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_team_assembled',
            field=models.BooleanField(default=False),
        ),
    ]
