# Generated by Django 2.2.3 on 2019-07-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_team_assembled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_team_assembled',
            new_name='team_assembled',
        ),
    ]
